//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Roma.proto
namespace Roma
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Message")]
  public partial class CS_Message : global::ProtoBuf.IExtensible
  {
    public CS_Message() {}
    
    private CS_Login _login = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CS_Login login
    {
      get { return _login; }
      set { _login = value; }
    }
    private CS_CreateRole _create_role = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"create_role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CS_CreateRole create_role
    {
      get { return _create_role; }
      set { _create_role = value; }
    }
    private CS_CreateRoom _create_room = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"create_room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CS_CreateRoom create_room
    {
      get { return _create_room; }
      set { _create_room = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Message")]
  public partial class SC_Message : global::ProtoBuf.IExtensible
  {
    public SC_Message() {}
    
    private int? _SC_Eno;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SC_Eno", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SC_Eno
    {
      get { return _SC_Eno?? default(int); }
      set { _SC_Eno = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SC_EnoSpecified
    {
      get { return this._SC_Eno != null; }
      set { if (value == (this._SC_Eno== null)) this._SC_Eno = value ? this.SC_Eno : (int?)null; }
    }
    private bool ShouldSerializeSC_Eno() { return SC_EnoSpecified; }
    private void ResetSC_Eno() { SC_EnoSpecified = false; }
    
    private SC_PlayerPublicData _PlayerPublicData = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PlayerPublicData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SC_PlayerPublicData PlayerPublicData
    {
      get { return _PlayerPublicData; }
      set { _PlayerPublicData = value; }
    }
    private SC_MatchResult _MatchResult = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"MatchResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SC_MatchResult MatchResult
    {
      get { return _MatchResult; }
      set { _MatchResult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Login")]
  public partial class CS_Login : global::ProtoBuf.IExtensible
  {
    public CS_Login() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _passWord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passWord
    {
      get { return _passWord; }
      set { _passWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CreateRole")]
  public partial class CS_CreateRole : global::ProtoBuf.IExtensible
  {
    public CS_CreateRole() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _icon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _gender;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_PlayerPublicData")]
  public partial class SC_PlayerPublicData : global::ProtoBuf.IExtensible
  {
    public SC_PlayerPublicData() {}
    
    private long _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _occ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"occ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occ
    {
      get { return _occ; }
      set { _occ = value; }
    }
    private int _resId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"resId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resId
    {
      get { return _resId; }
      set { _resId = value; }
    }
    private int _mapId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _dir;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_MatchResult")]
  public partial class SC_MatchResult : global::ProtoBuf.IExtensible
  {
    public SC_MatchResult() {}
    
    private int _matchType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"matchType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int matchType
    {
      get { return _matchType; }
      set { _matchType = value; }
    }
    private string _serverIp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serverIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverIp
    {
      get { return _serverIp; }
      set { _serverIp = value; }
    }
    private int _serverPort;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"serverPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverPort
    {
      get { return _serverPort; }
      set { _serverPort = value; }
    }
    private int _roomId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CreateRoom")]
  public partial class CS_CreateRoom : global::ProtoBuf.IExtensible
  {
    public CS_CreateRoom() {}
    
    private int _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private int _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_BattleInfo")]
  public partial class SC_BattleInfo : global::ProtoBuf.IExtensible
  {
    public SC_BattleInfo() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _mapType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapType
    {
      get { return _mapType; }
      set { _mapType = value; }
    }
    private readonly global::System.Collections.Generic.List<PlayerInfo> _playerInfo = new global::System.Collections.Generic.List<PlayerInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerInfo> playerInfo
    {
      get { return _playerInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private long? _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid?? default(long); }
      set { _uid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uidSpecified
    {
      get { return this._uid != null; }
      set { if (value == (this._uid== null)) this._uid = value ? this.uid : (long?)null; }
    }
    private bool ShouldSerializeuid() { return uidSpecified; }
    private void Resetuid() { uidSpecified = false; }
    
    private int? _heroIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroIndex
    {
      get { return _heroIndex?? default(int); }
      set { _heroIndex = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool heroIndexSpecified
    {
      get { return this._heroIndex != null; }
      set { if (value == (this._heroIndex== null)) this._heroIndex = value ? this.heroIndex : (int?)null; }
    }
    private bool ShouldSerializeheroIndex() { return heroIndexSpecified; }
    private void ResetheroIndex() { heroIndexSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}